/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendingMachine;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        VendingMachine vendingMachine=new VendingMachine();
        vendingMachine.AddItem("Snicker", ItemType.Snacks, 3, "Chcolate Bar");
        vendingMachine.AddItem("Lays", ItemType.Snacks, 1, "Potata Chips");
        vendingMachine.AddItem("Snicker", ItemType.Snacks, 1, "Chcolate Bar");
        vendingMachine.AddItem("Tuna Sandwish", ItemType.Snacks, 1, "Tuna Sandwish");
        vendingMachine.AddItem("Flafel", ItemType.Snacks, 2, "Sandwishes");
        vendingMachine.AddItem("Orange Juice", ItemType.ColdDrinks, 3, "Potata Chips");
        vendingMachine.AddItem("Latte", ItemType.HotDrinks, 2, "Potata Chips");
        vendingMachine.AddItem("Tea", ItemType.HotDrinks, 1, "Potata Chips");
        boolean strFlag=false;
        Scanner sc= new Scanner(System.in);
        while (!strFlag)
        {
            System.out.println("Press 'M' to insert Money ... Your current credit is : "+ vendingMachine.GetCredit());
            for (int i=0 ; i<vendingMachine.items.size() ; i++)
            {
                System.out.println(i + " - " + vendingMachine.items.get(i).name + " ........... "+vendingMachine.items.get(i).price+" JD's" );
            }
            String str= sc.nextLine();
            if (str.toLowerCase().equals("m"))
            {
                boolean success=false;
                while (!success){
                    System.out.println("Please Insert Money ... Allowed units: 1 JD , 5 JD's , 10 JD's");
                    int str2=sc.nextInt();
                    success=vendingMachine.addMoney(str2);
                }
                strFlag=true;
            }
        }

        while (vendingMachine.GetCredit()>0)
        {
            System.out.println("Press 'M' to insert money / 'I' to select an item ... your current credit is "+vendingMachine.GetCredit()+" JD");
            Scanner sc1= new Scanner(System.in);
            String str= sc1.nextLine();
            if (str.toLowerCase().equals("m"))
            {
                boolean success=false;
                while (!success){
                    System.out.println("Please Insert Money ... Allowed units: 1 JD , 5 JD's , 10 JD's");
                    int str2=sc1.nextInt();
                    success=vendingMachine.addMoney(str2);
                }
            }
            if (str.toLowerCase().equals("i"))
            {
                System.out.println("Enter the name of the Item: ");
                String item=sc1.nextLine();
                vendingMachine.BuyItem(item);
            }
        }



    }
}
